<?php

function get_countries () {
	// Country data set
	$countries = array();
	$countries['AF'] = array('name'=>'Afghanistan','currency'=>'AFA'); 
	$countries['AL'] = array('name'=>'Albania','currency'=>'ALL'); 
	$countries['DZ'] = array('name'=>'Algeria','currency'=>'DZD'); 
	$countries['AS'] = array('name'=>'American Samoa','currency'=>'USD'); 
	$countries['AD'] = array('name'=>'Andorra','currency'=>'EUR'); 
	$countries['AO'] = array('name'=>'Angola','currency'=>'AON'); 
	$countries['AI'] = array('name'=>'Anguilla','currency'=>'XCD'); 
	$countries['AQ'] = array('name'=>'Antarctica','currency'=>'ATA'); 
	$countries['AG'] = array('name'=>'Antigua and Barbuda','currency'=>'XCD'); 
	$countries['AR'] = array('name'=>'Argentina','currency'=>'ARS'); 
	$countries['AM'] = array('name'=>'Armenia','currency'=>'AMD'); 
	$countries['AW'] = array('name'=>'Aruba','currency'=>'AWG'); 
	$countries['AU'] = array('name'=>'Australia','currency'=>'AUD'); 
	$countries['AT'] = array('name'=>'Austria','currency'=>'EUR'); 
	$countries['AZ'] = array('name'=>'Azerbaijan','currency'=>'AZM'); 
	$countries['BS'] = array('name'=>'Bahamas','currency'=>'BSD'); 
	$countries['BH'] = array('name'=>'Bahrain','currency'=>'BHD'); 
	$countries['BD'] = array('name'=>'Bangladesh','currency'=>'BDT'); 
	$countries['BB'] = array('name'=>'Barbados','currency'=>'BBD'); 
	$countries['BY'] = array('name'=>'Belarus','currency'=>'BYB'); 
	$countries['BE'] = array('name'=>'Belgium','currency'=>'EUR'); 
	$countries['BZ'] = array('name'=>'Belize','currency'=>'BZD'); 
	$countries['BJ'] = array('name'=>'Benin','currency'=>'XOF'); 
	$countries['BM'] = array('name'=>'Bermuda','currency'=>'BMD'); 
	$countries['BT'] = array('name'=>'Bhutan','currency'=>'BTN'); 
	$countries['BO'] = array('name'=>'Bolivia','currency'=>'BOB'); 
	$countries['BA'] = array('name'=>'Bosnia-Herzegovina','currency'=>'BAM'); 
	$countries['BW'] = array('name'=>'Botswana','currency'=>'BWP'); 
	$countries['BV'] = array('name'=>'Bouvet Island','currency'=>'NOK'); 
	$countries['BR'] = array('name'=>'Brazil','currency'=>'BRL'); 
	$countries['IO'] = array('name'=>'British Indian Ocean Territory','currency'=>'USD'); 
	$countries['BN'] = array('name'=>'Brunei Darussalam','currency'=>'BND'); 
	$countries['BG'] = array('name'=>'Bulgaria','currency'=>'BGL'); 
	$countries['BF'] = array('name'=>'Burkina Faso','currency'=>'XOF'); 
	$countries['BI'] = array('name'=>'Burundi','currency'=>'BIF'); 
	$countries['KH'] = array('name'=>'Cambodia','currency'=>'KHR'); 
	$countries['CM'] = array('name'=>'Cameroon','currency'=>'XAF'); 
	$countries['CA'] = array('name'=>'Canada','currency'=>'CAD'); 
	$countries['CV'] = array('name'=>'Cape Verde','currency'=>'CVE'); 
	$countries['KY'] = array('name'=>'Cayman Islands','currency'=>'KYD'); 
	$countries['CF'] = array('name'=>'Central African Republic','currency'=>'XAF'); 
	$countries['TD'] = array('name'=>'Chad','currency'=>'XAF'); 
	$countries['CL'] = array('name'=>'Chile','currency'=>'CLP'); 
	$countries['CN'] = array('name'=>'China','currency'=>'CNY'); 
	$countries['CX'] = array('name'=>'Christmas Island','currency'=>'AUD'); 
	$countries['CC'] = array('name'=>'Cocos (Keeling) Islands','currency'=>'AUD'); 
	$countries['CO'] = array('name'=>'Colombia','currency'=>'COP'); 
	$countries['KM'] = array('name'=>'Comoros','currency'=>'KMF'); 
	$countries['CG'] = array('name'=>'Congo','currency'=>'XAF'); 
	$countries['CK'] = array('name'=>'Cook Islands','currency'=>'NZD'); 
	$countries['CR'] = array('name'=>'Costa Rica','currency'=>'CRC'); 
	$countries['HR'] = array('name'=>'Croatia','currency'=>'HRK'); 
	$countries['CU'] = array('name'=>'Cuba','currency'=>'CUP'); 
	$countries['CY'] = array('name'=>'Cyprus','currency'=>'CYP'); 
	$countries['CZ'] = array('name'=>'Czech Rep.','currency'=>'CZK'); 
	$countries['CD'] = array('name'=>'Democratic Republic of Congo','currency'=>'CDF'); 
	$countries['DK'] = array('name'=>'Denmark','currency'=>'DKK'); 
	$countries['DE'] = array('name'=>'Deutschland','currency'=>'EUR'); 
	$countries['DJ'] = array('name'=>'Djibouti','currency'=>'DJF'); 
	$countries['DM'] = array('name'=>'Dominica','currency'=>'XCD'); 
	$countries['DO'] = array('name'=>'Dominican Republic','currency'=>'DOP'); 
	$countries['TP'] = array('name'=>'East Timor','currency'=>'TPE'); 
	$countries['EC'] = array('name'=>'Ecuador','currency'=>'ECS'); 
	$countries['EG'] = array('name'=>'Egypt','currency'=>'EGP'); 
	$countries['SV'] = array('name'=>'El Salvador','currency'=>'SVC'); 
	$countries['GQ'] = array('name'=>'Equatorial Guinea','currency'=>'XAF'); 
	$countries['ER'] = array('name'=>'Eritrea','currency'=>'ERN'); 
	$countries['EE'] = array('name'=>'Estonia','currency'=>'EEK'); 
	$countries['ET'] = array('name'=>'Ethiopia','currency'=>'ETB'); 
	$countries['FK'] = array('name'=>'Falkland Islands','currency'=>'FKP'); 
	$countries['FO'] = array('name'=>'Faroe Islands','currency'=>'DKK'); 
	$countries['FJ'] = array('name'=>'Fiji','currency'=>'FJD'); 
	$countries['FI'] = array('name'=>'Finland','currency'=>'EUR'); 
	$countries['FR'] = array('name'=>'France','currency'=>'EUR'); 
	$countries['TF'] = array('name'=>'French Southern Territories','currency'=>'EUR'); 
	$countries['GA'] = array('name'=>'Gabon','currency'=>'XAF'); 
	$countries['GM'] = array('name'=>'Gambia','currency'=>'GMD'); 
	$countries['GE'] = array('name'=>'Georgia','currency'=>'GEL'); 
	$countries['DE'] = array('name'=>'Germany','currency'=>'EUR'); 
	$countries['GH'] = array('name'=>'Ghana','currency'=>'GHC'); 
	$countries['GI'] = array('name'=>'Gibraltar','currency'=>'GIP'); 
	$countries['GB'] = array('name'=>'Great Britain','currency'=>'GBP'); 
	$countries['GR'] = array('name'=>'Greece','currency'=>'EUR'); 
	$countries['GL'] = array('name'=>'Greenland','currency'=>'DKK'); 
	$countries['GD'] = array('name'=>'Grenada','currency'=>'XCD'); 
	$countries['GP'] = array('name'=>'Guadeloupe (French)','currency'=>'EUR'); 
	$countries['GU'] = array('name'=>'Guam (USA)','currency'=>'USD'); 
	$countries['GT'] = array('name'=>'Guatemala','currency'=>'QTQ'); 
	$countries['GF'] = array('name'=>'Guernsey','currency'=>'GBP'); 
	$countries['GN'] = array('name'=>'Guinea','currency'=>'GNF'); 
	$countries['GW'] = array('name'=>'Guinea Bissau','currency'=>'GWP'); 
	$countries['GY'] = array('name'=>'Guyana','currency'=>'GYD'); 
	$countries['HT'] = array('name'=>'Haiti','currency'=>'HTG'); 
	$countries['HM'] = array('name'=>'Heard Island and McDonald Islands','currency'=>'AUD'); 
	$countries['HN'] = array('name'=>'Honduras','currency'=>'HNL'); 
	$countries['HK'] = array('name'=>'Hong Kong','currency'=>'HKD'); 
	$countries['HU'] = array('name'=>'Hungary','currency'=>'HUF'); 
	$countries['IS'] = array('name'=>'Iceland','currency'=>'ISK'); 
	$countries['IN'] = array('name'=>'India','currency'=>'INR'); 
	$countries['ID'] = array('name'=>'Indonesia','currency'=>'IDR'); 
	$countries['IR'] = array('name'=>'Iran','currency'=>'IRR'); 
	$countries['IQ'] = array('name'=>'Iraq','currency'=>'IQD'); 
	$countries['IE'] = array('name'=>'Ireland','currency'=>'EUR'); 
	$countries['IM'] = array('name'=>'Isle of Man','currency'=>'GBP'); 
	$countries['IL'] = array('name'=>'Israel','currency'=>'ILS'); 
	$countries['IT'] = array('name'=>'Italy','currency'=>'EUR'); 
	$countries['CI'] = array('name'=>'Ivory Coast','currency'=>'XOF'); 
	$countries['JM'] = array('name'=>'Jamaica','currency'=>'JMD'); 
	$countries['JP'] = array('name'=>'Japan','currency'=>'JPY'); 
	$countries['JE'] = array('name'=>'Jersey','currency'=>'GBP'); 
	$countries['JO'] = array('name'=>'Jordan','currency'=>'JOD'); 
	$countries['KZ'] = array('name'=>'Kazakhstan','currency'=>'KZT'); 
	$countries['KE'] = array('name'=>'Kenya','currency'=>'KES'); 
	$countries['KI'] = array('name'=>'Kiribati','currency'=>'AUD'); 
	$countries['KP'] = array('name'=>'Korea, North','currency'=>'KPW'); 
	$countries['KR'] = array('name'=>'Korea, South','currency'=>'KRW'); 
	$countries['KW'] = array('name'=>'Kuwait','currency'=>'KWD'); 
	$countries['KG'] = array('name'=>'Kyrgyzstan','currency'=>'KGS'); 
	$countries['LA'] = array('name'=>'Laos','currency'=>'LAK'); 
	$countries['LV'] = array('name'=>'Latvia','currency'=>'LVL'); 
	$countries['LB'] = array('name'=>'Lebanon','currency'=>'LBP'); 
	$countries['LS'] = array('name'=>'Lesotho','currency'=>'LSL'); 
	$countries['LR'] = array('name'=>'Liberia','currency'=>'LRD'); 
	$countries['LY'] = array('name'=>'Libya','currency'=>'LYD'); 
	$countries['LI'] = array('name'=>'Liechtenstein','currency'=>'CHF'); 
	$countries['LT'] = array('name'=>'Lithuania','currency'=>'LTL'); 
	$countries['LU'] = array('name'=>'Luxembourg','currency'=>'EUR'); 
	$countries['MO'] = array('name'=>'Macau','currency'=>'MOP'); 
	$countries['MK'] = array('name'=>'Macedonia','currency'=>'MKD'); 
	$countries['MG'] = array('name'=>'Madagascar','currency'=>'MGF'); 
	$countries['MW'] = array('name'=>'Malawi','currency'=>'MWK'); 
	$countries['MY'] = array('name'=>'Malaysia','currency'=>'MYR'); 
	$countries['MV'] = array('name'=>'Maldives','currency'=>'MVR'); 
	$countries['ML'] = array('name'=>'Mali','currency'=>'XOF'); 
	$countries['MT'] = array('name'=>'Malta','currency'=>'MTL'); 
	$countries['MH'] = array('name'=>'Marshall Islands','currency'=>'USD'); 
	$countries['MQ'] = array('name'=>'Martinique (French)','currency'=>'EUR'); 
	$countries['MR'] = array('name'=>'Mauritania','currency'=>'MRO'); 
	$countries['MU'] = array('name'=>'Mauritius','currency'=>'MUR'); 
	$countries['YT'] = array('name'=>'Mayotte','currency'=>'EUR'); 
	$countries['MX'] = array('name'=>'Mexico','currency'=>'MXN'); 
	$countries['FM'] = array('name'=>'Micronesia','currency'=>'USD'); 
	$countries['MD'] = array('name'=>'Moldova','currency'=>'MDL'); 
	$countries['MC'] = array('name'=>'Monaco','currency'=>'EUR'); 
	$countries['MN'] = array('name'=>'Mongolia','currency'=>'MNT'); 
	$countries['MS'] = array('name'=>'Montserrat','currency'=>'XCD'); 
	$countries['MA'] = array('name'=>'Morocco','currency'=>'MAD'); 
	$countries['MZ'] = array('name'=>'Mozambique','currency'=>'MZM'); 
	$countries['MM'] = array('name'=>'Myanmar','currency'=>'MMK'); 
	$countries['NA'] = array('name'=>'Namibia','currency'=>'NAD'); 
	$countries['NR'] = array('name'=>'Nauru','currency'=>'AUD'); 
	$countries['NP'] = array('name'=>'Nepal','currency'=>'NPR'); 
	$countries['NL'] = array('name'=>'Netherlands','currency'=>'EUR'); 
	$countries['AN'] = array('name'=>'Netherlands Antilles','currency'=>'ANG'); 
	$countries['NC'] = array('name'=>'New Caledonia (French)','currency'=>'XPF'); 
	$countries['NZ'] = array('name'=>'New Zealand','currency'=>'NZD'); 
	$countries['NI'] = array('name'=>'Nicaragua','currency'=>'NIC'); 
	$countries['NE'] = array('name'=>'Niger','currency'=>'XOF'); 
	$countries['NG'] = array('name'=>'Nigeria','currency'=>'NGN'); 
	$countries['NU'] = array('name'=>'Niue','currency'=>'NZD'); 
	$countries['NF'] = array('name'=>'Norfolk Island','currency'=>'AUD'); 
	$countries['MP'] = array('name'=>'Northern Mariana Islands','currency'=>'USD'); 
	$countries['NO'] = array('name'=>'Norway','currency'=>'NOK'); 
	$countries['OM'] = array('name'=>'Oman','currency'=>'OMR'); 
	$countries['PK'] = array('name'=>'Pakistan','currency'=>'PKR'); 
	$countries['PW'] = array('name'=>'Palau','currency'=>'USD'); 
	$countries['PA'] = array('name'=>'Panama','currency'=>'PAB'); 
	$countries['PG'] = array('name'=>'Papua New Guinea','currency'=>'PGK'); 
	$countries['PY'] = array('name'=>'Paraguay','currency'=>'PYG'); 
	$countries['PE'] = array('name'=>'Peru','currency'=>'PEN'); 
	$countries['PH'] = array('name'=>'Philippines','currency'=>'PHP'); 
	$countries['PN'] = array('name'=>'Pitcairn Island','currency'=>'NZD'); 
	$countries['PL'] = array('name'=>'Poland','currency'=>'PLZ'); 
	$countries['PF'] = array('name'=>'Polynesia (French)','currency'=>'XPF'); 
	$countries['PT'] = array('name'=>'Portugal','currency'=>'EUR'); 
	$countries['PR'] = array('name'=>'Puerto Rico','currency'=>'USD'); 
	$countries['QA'] = array('name'=>'Qatar','currency'=>'QAR'); 
	$countries['RE'] = array('name'=>'Reunion (French)','currency'=>'EUR'); 
	$countries['RO'] = array('name'=>'Romania','currency'=>'ROL'); 
	$countries['RU'] = array('name'=>'Russia','currency'=>'RUR'); 
	$countries['RW'] = array('name'=>'Rwanda','currency'=>'RWF'); 
	$countries['SH'] = array('name'=>'Saint Helena','currency'=>'SHP'); 
	$countries['KN'] = array('name'=>'Saint Kitts & Nevis Anguilla','currency'=>'XCD'); 
	$countries['LC'] = array('name'=>'Saint Lucia','currency'=>'XCD'); 
	$countries['PM'] = array('name'=>'Saint Pierre and Miquelon','currency'=>'EUR'); 
	$countries['VC'] = array('name'=>'Saint Vincent & Grenadines','currency'=>'XCD'); 
	$countries['WS'] = array('name'=>'Samoa','currency'=>'WST'); 
	$countries['SM'] = array('name'=>'San Marino','currency'=>'ITL'); 
	$countries['ST'] = array('name'=>'Sao Tome and Principe','currency'=>'STD'); 
	$countries['SA'] = array('name'=>'Saudi Arabia','currency'=>'SAR'); 
	$countries['SN'] = array('name'=>'Senegal','currency'=>'XOF'); 
	$countries['SC'] = array('name'=>'Seychelles','currency'=>'SCR'); 
	$countries['SL'] = array('name'=>'Sierra Leone','currency'=>'SLL'); 
	$countries['SG'] = array('name'=>'Singapore','currency'=>'SGD'); 
	$countries['SK'] = array('name'=>'Slovakia','currency'=>'SKK'); 
	$countries['SI'] = array('name'=>'Slovenia','currency'=>'SIT'); 
	$countries['SB'] = array('name'=>'Solomon Islands','currency'=>'SBD'); 
	$countries['SO'] = array('name'=>'Somalia','currency'=>'SOD'); 
	$countries['ZA'] = array('name'=>'South Africa','currency'=>'ZAR'); 
	$countries['GS'] = array('name'=>'South Georgia & South Sandwich Islands','currency'=>'GBP'); 
	$countries['ES'] = array('name'=>'Spain','currency'=>'EUR'); 
	$countries['LK'] = array('name'=>'Sri Lanka','currency'=>'LKR'); 
	$countries['SD'] = array('name'=>'Sudan','currency'=>'SDD'); 
	$countries['SR'] = array('name'=>'Suriname','currency'=>'SRG'); 
	$countries['SJ'] = array('name'=>'Svalbard and Jan Mayen Islands','currency'=>'NOK'); 
	$countries['SZ'] = array('name'=>'Swaziland','currency'=>'SZL'); 
	$countries['SE'] = array('name'=>'Sweden','currency'=>'SEK'); 
	$countries['CH'] = array('name'=>'Switzerland','currency'=>'CHF'); 
	$countries['SY'] = array('name'=>'Syria','currency'=>'SYP'); 
	$countries['TW'] = array('name'=>'Taiwan','currency'=>'TWD'); 
	$countries['TJ'] = array('name'=>'Tajikistan','currency'=>'TJR'); 
	$countries['TZ'] = array('name'=>'Tanzania','currency'=>'TZS'); 
	$countries['TH'] = array('name'=>'Thailand','currency'=>'THB'); 
	$countries['TG'] = array('name'=>'Togo','currency'=>'XOF'); 
	$countries['TK'] = array('name'=>'Tokelau','currency'=>'NZD'); 
	$countries['TO'] = array('name'=>'Tonga','currency'=>'TOP'); 
	$countries['TT'] = array('name'=>'Trinidad and Tobago','currency'=>'TTD'); 
	$countries['TN'] = array('name'=>'Tunisia','currency'=>'TND'); 
	$countries['TR'] = array('name'=>'Turkey','currency'=>'TRL'); 
	$countries['TM'] = array('name'=>'Turkmenistan','currency'=>'TMM'); 
	$countries['TC'] = array('name'=>'Turks and Caicos Islands','currency'=>'USD'); 
	$countries['TV'] = array('name'=>'Tuvalu','currency'=>'AUD'); 
	$countries['UK'] = array('name'=>'U.K.','currency'=>'GBP'); 
	$countries['UG'] = array('name'=>'Uganda','currency'=>'UGS'); 
	$countries['UA'] = array('name'=>'Ukraine','currency'=>'UAG'); 
	$countries['AE'] = array('name'=>'United Arab Emirates','currency'=>'AED'); 
	$countries['UY'] = array('name'=>'Uruguay','currency'=>'UYP'); 
	$countries['US'] = array('name'=>'USA','currency'=>'USD'); 
	$countries['UM'] = array('name'=>'USA Minor Outlying Islands','currency'=>'USD'); 
	$countries['UZ'] = array('name'=>'Uzbekistan','currency'=>'UZS'); 
	$countries['VU'] = array('name'=>'Vanuatu','currency'=>'VUV'); 
	$countries['VA'] = array('name'=>'Vatican','currency'=>'EUR'); 
	$countries['VE'] = array('name'=>'Venezuela','currency'=>'VUB'); 
	$countries['VN'] = array('name'=>'Vietnam','currency'=>'VND'); 
	$countries['VG'] = array('name'=>'Virgin Islands (British)','currency'=>'USD'); 
	$countries['VI'] = array('name'=>'Virgin Islands (USA)','currency'=>'USD'); 
	$countries['WF'] = array('name'=>'Wallis and Futuna Islands','currency'=>'XPF'); 
	$countries['EH'] = array('name'=>'Western Sahara','currency'=>'MAD'); 
	$countries['YE'] = array('name'=>'Yemen','currency'=>'YER'); 
	$countries['YU'] = array('name'=>'Yugoslavia','currency'=>'YUN'); 
	$countries['ZM'] = array('name'=>'Zambia','currency'=>'ZMK'); 
	$countries['ZW'] = array('name'=>'Zimbabwe','currency'=>'ZWD');
	return $countries;
}

function get_country_regions() {
	$regions = array();
	$regions['AU'] = array();
	$regions['AU']['NSW'] = 'New South Wales';
	$regions['AU']['NT'] = 'Northern Territory';
	$regions['AU']['QLD'] = 'Queensland';
	$regions['AU']['TAS'] = 'Tasmania';
	$regions['AU']['VIC'] = 'Victoria';
	$regions['AU']['WA'] = 'Western Australia';

	$regions['CA'] = array();
	$regions['CA']['AB'] = 'Alberta';
	$regions['CA']['BC'] = 'British Columbia';
	$regions['CA']['MB'] = 'Manitoba';
	$regions['CA']['NB'] = 'New Brunswick';
	$regions['CA']['NF'] = 'Newfoundland';
	$regions['CA']['NT'] = 'Northwest Territories';
	$regions['CA']['NS'] = 'Nova Scotia';
	$regions['CA']['NU'] = 'Nunavut';
	$regions['CA']['ON'] = 'Ontario';
	$regions['CA']['PE'] = 'Prince Edward Island';
	$regions['CA']['PQ'] = 'Quebec';
	$regions['CA']['SK'] = 'Saskatchewan';
	$regions['CA']['YT'] = 'Yukon Territory';

	$regions['US'] = array();
	$regions['US']['AL'] = 'Alabama';
	$regions['US']['AK'] = 'Alaska ';
	$regions['US']['AZ'] = 'Arizona';
	$regions['US']['AR'] = 'Arkansas';
	$regions['US']['CA'] = 'California ';
	$regions['US']['CO'] = 'Colorado';
	$regions['US']['CT'] = 'Connecticut';
	$regions['US']['DE'] = 'Delaware';
	$regions['US']['DC'] = 'District Of Columbia ';
	$regions['US']['FL'] = 'Florida';
	$regions['US']['GA'] = 'Georgia ';
	$regions['US']['HI'] = 'Hawaii';
	$regions['US']['ID'] = 'Idaho';
	$regions['US']['IL'] = 'Illinois';
	$regions['US']['IN'] = 'Indiana';
	$regions['US']['IA'] = 'Iowa';
	$regions['US']['KS'] = 'Kansas';
	$regions['US']['KY'] = 'Kentucky';
	$regions['US']['LA'] = 'Louisiana';
	$regions['US']['ME'] = 'Maine';
	$regions['US']['MD'] = 'Maryland';
	$regions['US']['MA'] = 'Massachusetts';
	$regions['US']['MI'] = 'Michigan';
	$regions['US']['MN'] = 'Minnesota';
	$regions['US']['MS'] = 'Mississippi';
	$regions['US']['MO'] = 'Missouri';
	$regions['US']['MT'] = 'Montana';
	$regions['US']['NE'] = 'Nebraska';
	$regions['US']['NV'] = 'Nevada';
	$regions['US']['NH'] = 'New Hampshire';
	$regions['US']['NJ'] = 'New Jersey';
	$regions['US']['NM'] = 'New Mexico';
	$regions['US']['NY'] = 'New York';
	$regions['US']['NC'] = 'North Carolina';
	$regions['US']['ND'] = 'North Dakota';
	$regions['US']['OH'] = 'Ohio';
	$regions['US']['OK'] = 'Oklahoma';
	$regions['US']['OR'] = 'Oregon';
	$regions['US']['PA'] = 'Pennsylvania';
	$regions['US']['RI'] = 'Rhode Island';
	$regions['US']['SC'] = 'South Carolina';
	$regions['US']['SD'] = 'South Dakota';
	$regions['US']['TN'] = 'Tennessee';
	$regions['US']['TX'] = 'Texas';
	$regions['US']['UT'] = 'Utah';
	$regions['US']['VT'] = 'Vermont';
	$regions['US']['VA'] = 'Virginia';
	$regions['US']['WA'] = 'Washington';
	$regions['US']['WV'] = 'West Virginia';
	$regions['US']['WI'] = 'Wisconsin';
	$regions['US']['WY'] = 'Wyoming';
	return $regions;
}


function get_currencies () {
	// Currency data set
	$currencies = array();
	$currencies['AED'] = array('name'=>'Arab Emirates Dirham','symbol'=>'','entity'=>''); 
	$currencies['AFA'] = array('name'=>'Afghanistan Afghani','symbol'=>'','entity'=>''); 
	$currencies['ALL'] = array('name'=>'Albanian Lek','symbol'=>'','entity'=>''); 
	$currencies['AMD'] = array('name'=>'Armenian Dram','symbol'=>'','entity'=>''); 
	$currencies['ANG'] = array('name'=>'Netherlands Antillean Guilder','symbol'=>'','entity'=>''); 
	$currencies['AON'] = array('name'=>'Angolan New Kwanza','symbol'=>'','entity'=>''); 
	$currencies['ARS'] = array('name'=>'Argentine Peso','symbol'=>'','entity'=>''); 
	$currencies['ATA'] = array('name'=>'Dollar','symbol'=>'$','entity'=>'&#036;'); 
	$currencies['AUD'] = array('name'=>'Australian Dollar','symbol'=>'$','entity'=>'&#036;'); 
	$currencies['AWG'] = array('name'=>'Aruban Guilder','symbol'=>'','entity'=>''); 
	$currencies['AZM'] = array('name'=>'Azerbaijanian Manat','symbol'=>'','entity'=>''); 
	$currencies['BAM'] = array('name'=>'Marka','symbol'=>'','entity'=>''); 
	$currencies['BBD'] = array('name'=>'Barbados Dollar','symbol'=>'$','entity'=>'&#036;'); 
	$currencies['BDT'] = array('name'=>'Bangladeshi Taka','symbol'=>'','entity'=>''); 
	$currencies['BGL'] = array('name'=>'Bulgarian Lev','symbol'=>'','entity'=>''); 
	$currencies['BHD'] = array('name'=>'Bahraini Dinar','symbol'=>'','entity'=>''); 
	$currencies['BIF'] = array('name'=>'Burundi Franc','symbol'=>'','entity'=>''); 
	$currencies['BMD'] = array('name'=>'Bermudian Dollar','symbol'=>'$','entity'=>'&#036;'); 
	$currencies['BND'] = array('name'=>'Brunei Dollar','symbol'=>'$','entity'=>'&#036;'); 
	$currencies['BOB'] = array('name'=>'Boliviano','symbol'=>'','entity'=>''); 
	$currencies['BRL'] = array('name'=>'Brazilian Real','symbol'=>'','entity'=>''); 
	$currencies['BSD'] = array('name'=>'Bahamian Dollar','symbol'=>'$','entity'=>'&#036;'); 
	$currencies['BTN'] = array('name'=>'Bhutan Ngultrum','symbol'=>'','entity'=>''); 
	$currencies['BWP'] = array('name'=>'Botswana Pula','symbol'=>'','entity'=>''); 
	$currencies['BYB'] = array('name'=>'Belarussian Ruble','symbol'=>'','entity'=>''); 
	$currencies['BZD'] = array('name'=>'Belize Dollar','symbol'=>'$','entity'=>'&#036;'); 
	$currencies['CAD'] = array('name'=>'Canadian Dollar','symbol'=>'$','entity'=>'&#036;'); 
	$currencies['CDF'] = array('name'=>'Francs','symbol'=>'','entity'=>''); 
	$currencies['CHF'] = array('name'=>'Swiss Franc','symbol'=>'','entity'=>''); 
	$currencies['CLP'] = array('name'=>'Chilean Peso','symbol'=>'','entity'=>''); 
	$currencies['CNY'] = array('name'=>'Yuan Renminbi','symbol'=>'','entity'=>''); 
	$currencies['COP'] = array('name'=>'Colombian Peso','symbol'=>'','entity'=>''); 
	$currencies['CRC'] = array('name'=>'Costa Rican Colon','symbol'=>'','entity'=>''); 
	$currencies['CUP'] = array('name'=>'Cuban Peso','symbol'=>'','entity'=>''); 
	$currencies['CVE'] = array('name'=>'Cape Verde Escudo','symbol'=>'','entity'=>''); 
	$currencies['CYP'] = array('name'=>'Cyprus Pound','symbol'=>'','entity'=>''); 
	$currencies['CZK'] = array('name'=>'Czech Koruna','symbol'=>'','entity'=>''); 
	$currencies['DJF'] = array('name'=>'Djibouti Franc','symbol'=>'','entity'=>''); 
	$currencies['DKK'] = array('name'=>'Danish Krone','symbol'=>'','entity'=>''); 
	$currencies['DOP'] = array('name'=>'Dominican Peso','symbol'=>'','entity'=>''); 
	$currencies['DZD'] = array('name'=>'Algerian Dinar','symbol'=>'','entity'=>''); 
	$currencies['ECS'] = array('name'=>'Ecuador Sucre','symbol'=>'','entity'=>''); 
	$currencies['EEK'] = array('name'=>'Estonian Kroon','symbol'=>'','entity'=>''); 
	$currencies['EGP'] = array('name'=>'Egyptian Pound','symbol'=>'','entity'=>''); 
	$currencies['ERN'] = array('name'=>'Eritrean Nakfa','symbol'=>'','entity'=>''); 
	$currencies['ETB'] = array('name'=>'Ethiopian Birr','symbol'=>'','entity'=>''); 
	$currencies['EUR'] = array('name'=>'Euro','symbol'=>'€','entity'=>'&#8364;'); 
	$currencies['FJD'] = array('name'=>'Fiji Dollar','symbol'=>'$','entity'=>'&#036;'); 
	$currencies['FKP'] = array('name'=>'Falkland Islands Pound','symbol'=>'','entity'=>''); 
	$currencies['GBP'] = array('name'=>'Pound Sterling','symbol'=>'£','entity'=>'&#163;'); 
	$currencies['GEL'] = array('name'=>'Georgian Lari','symbol'=>'','entity'=>''); 
	$currencies['GHC'] = array('name'=>'Ghanaian Cedi','symbol'=>'','entity'=>''); 
	$currencies['GIP'] = array('name'=>'Gibraltar Pound','symbol'=>'','entity'=>''); 
	$currencies['GMD'] = array('name'=>'Gambian Dalasi','symbol'=>'','entity'=>''); 
	$currencies['GNF'] = array('name'=>'Guinea Franc','symbol'=>'','entity'=>''); 
	$currencies['GWP'] = array('name'=>'Guinea-Bissau Peso','symbol'=>'','entity'=>''); 
	$currencies['GYD'] = array('name'=>'Guyana Dollar','symbol'=>'$','entity'=>'&#036;'); 
	$currencies['HKD'] = array('name'=>'Hong Kong Dollar','symbol'=>'$','entity'=>'&#036;'); 
	$currencies['HNL'] = array('name'=>'Honduran Lempira','symbol'=>'','entity'=>''); 
	$currencies['HRK'] = array('name'=>'Croatian Kuna','symbol'=>'','entity'=>''); 
	$currencies['HTG'] = array('name'=>'Haitian Gourde','symbol'=>'','entity'=>''); 
	$currencies['HUF'] = array('name'=>'Hungarian Forint','symbol'=>'','entity'=>''); 
	$currencies['IDR'] = array('name'=>'Indonesian Rupiah','symbol'=>'','entity'=>''); 
	$currencies['ILS'] = array('name'=>'Israeli New Shekel','symbol'=>'','entity'=>''); 
	$currencies['INR'] = array('name'=>'Indian Rupee','symbol'=>'','entity'=>''); 
	$currencies['IQD'] = array('name'=>'Iraqi Dinar','symbol'=>'','entity'=>''); 
	$currencies['IRR'] = array('name'=>'Iranian Rial','symbol'=>'','entity'=>''); 
	$currencies['ISK'] = array('name'=>'Iceland Krona','symbol'=>'','entity'=>''); 
	$currencies['ITL'] = array('name'=>'Italian Lira','symbol'=>'','entity'=>''); 
	$currencies['JMD'] = array('name'=>'Jamaican Dollar','symbol'=>'$','entity'=>'&#036;'); 
	$currencies['JOD'] = array('name'=>'Jordanian Dinar','symbol'=>'','entity'=>''); 
	$currencies['JPY'] = array('name'=>'Japanese Yen','symbol'=>'¥','entity'=>'&#165;'); 
	$currencies['KES'] = array('name'=>'Kenyan Shilling','symbol'=>'','entity'=>''); 
	$currencies['KGS'] = array('name'=>'Som','symbol'=>'','entity'=>''); 
	$currencies['KHR'] = array('name'=>'Kampuchean Riel','symbol'=>'','entity'=>''); 
	$currencies['KMF'] = array('name'=>'Comoros Franc','symbol'=>'','entity'=>''); 
	$currencies['KPW'] = array('name'=>'North Korean Won','symbol'=>'','entity'=>''); 
	$currencies['KRW'] = array('name'=>'Korean Won','symbol'=>'','entity'=>''); 
	$currencies['KWD'] = array('name'=>'Kuwaiti Dinar','symbol'=>'','entity'=>''); 
	$currencies['KYD'] = array('name'=>'Cayman Islands Dollar','symbol'=>'$','entity'=>'&#036;'); 
	$currencies['KZT'] = array('name'=>'Kazakhstan Tenge','symbol'=>'','entity'=>''); 
	$currencies['LAK'] = array('name'=>'Lao Kip','symbol'=>'','entity'=>''); 
	$currencies['LBP'] = array('name'=>'Lebanese Pound','symbol'=>'','entity'=>''); 
	$currencies['LKR'] = array('name'=>'Sri Lanka Rupee','symbol'=>'','entity'=>''); 
	$currencies['LRD'] = array('name'=>'Liberian Dollar','symbol'=>'$','entity'=>'&#036;'); 
	$currencies['LSL'] = array('name'=>'Lesotho Loti','symbol'=>'','entity'=>''); 
	$currencies['LTL'] = array('name'=>'Lithuanian Litas','symbol'=>'','entity'=>''); 
	$currencies['LVL'] = array('name'=>'Latvian Lats','symbol'=>'','entity'=>''); 
	$currencies['LYD'] = array('name'=>'Libyan Dinar','symbol'=>'','entity'=>''); 
	$currencies['MAD'] = array('name'=>'Moroccan Dirham','symbol'=>'','entity'=>''); 
	$currencies['MDL'] = array('name'=>'Moldovan Leu','symbol'=>'','entity'=>''); 
	$currencies['MGF'] = array('name'=>'Malagasy Franc','symbol'=>'','entity'=>''); 
	$currencies['MKD'] = array('name'=>'Denar','symbol'=>'','entity'=>''); 
	$currencies['MMK'] = array('name'=>'Myanmar Kyat','symbol'=>'','entity'=>''); 
	$currencies['MNT'] = array('name'=>'Mongolian Tugrik','symbol'=>'','entity'=>''); 
	$currencies['MOP'] = array('name'=>'Macau Pataca','symbol'=>'','entity'=>''); 
	$currencies['MRO'] = array('name'=>'Mauritanian Ouguiya','symbol'=>'','entity'=>''); 
	$currencies['MTL'] = array('name'=>'Maltese Lira','symbol'=>'','entity'=>''); 
	$currencies['MUR'] = array('name'=>'Mauritius Rupee','symbol'=>'','entity'=>''); 
	$currencies['MVR'] = array('name'=>'Maldive Rufiyaa','symbol'=>'','entity'=>''); 
	$currencies['MWK'] = array('name'=>'Malawi Kwacha','symbol'=>'','entity'=>''); 
	$currencies['MXN'] = array('name'=>'Mexican Nuevo Peso','symbol'=>'','entity'=>''); 
	$currencies['MYR'] = array('name'=>'Malaysian Ringgit','symbol'=>'','entity'=>''); 
	$currencies['MZM'] = array('name'=>'Mozambique Metical','symbol'=>'','entity'=>''); 
	$currencies['NAD'] = array('name'=>'Namibian Dollar','symbol'=>'$','entity'=>'&#036;'); 
	$currencies['NGN'] = array('name'=>'Nigerian Naira','symbol'=>'','entity'=>''); 
	$currencies['NIC'] = array('name'=>'Nicaraguan Cordoba Oro','symbol'=>'','entity'=>''); 
	$currencies['NOK'] = array('name'=>'Norwegian Krone','symbol'=>'','entity'=>''); 
	$currencies['NPR'] = array('name'=>'Nepalese Rupee','symbol'=>'','entity'=>''); 
	$currencies['NZD'] = array('name'=>'New Zealand Dollar','symbol'=>'$','entity'=>'&#036;'); 
	$currencies['OMR'] = array('name'=>'Omani Rial','symbol'=>'','entity'=>''); 
	$currencies['PAB'] = array('name'=>'Panamanian Balboa','symbol'=>'','entity'=>''); 
	$currencies['PEN'] = array('name'=>'Peruvian Nuevo Sol','symbol'=>'','entity'=>''); 
	$currencies['PGK'] = array('name'=>'Papua New Guinea Kina','symbol'=>'','entity'=>''); 
	$currencies['PHP'] = array('name'=>'Philippine Peso','symbol'=>'','entity'=>''); 
	$currencies['PKR'] = array('name'=>'Pakistan Rupee','symbol'=>'','entity'=>''); 
	$currencies['PLZ'] = array('name'=>'Polish Zloty','symbol'=>'','entity'=>''); 
	$currencies['PYG'] = array('name'=>'Paraguay Guarani','symbol'=>'','entity'=>''); 
	$currencies['QAR'] = array('name'=>'Qatari Rial','symbol'=>'','entity'=>''); 
	$currencies['QTQ'] = array('name'=>'Guatemalan Quetzal','symbol'=>'','entity'=>''); 
	$currencies['ROL'] = array('name'=>'Romanian Leu','symbol'=>'','entity'=>''); 
	$currencies['RUR'] = array('name'=>'Russian Ruble','symbol'=>'','entity'=>''); 
	$currencies['RWF'] = array('name'=>'Rwanda Franc','symbol'=>'','entity'=>''); 
	$currencies['SAR'] = array('name'=>'Saudi Riyal','symbol'=>'','entity'=>''); 
	$currencies['SBD'] = array('name'=>'Solomon Islands Dollar','symbol'=>'$','entity'=>'&#036;'); 
	$currencies['SCR'] = array('name'=>'Seychelles Rupee','symbol'=>'','entity'=>''); 
	$currencies['SDD'] = array('name'=>'Sudanese Dinar','symbol'=>'','entity'=>''); 
	$currencies['SEK'] = array('name'=>'Swedish Krona','symbol'=>'','entity'=>''); 
	$currencies['SGD'] = array('name'=>'Singapore Dollar','symbol'=>'$','entity'=>'&#036;'); 
	$currencies['SHP'] = array('name'=>'St. Helena Pound','symbol'=>'','entity'=>''); 
	$currencies['SIT'] = array('name'=>'Slovenian Tolar','symbol'=>'','entity'=>''); 
	$currencies['SKK'] = array('name'=>'Slovak Koruna','symbol'=>'','entity'=>''); 
	$currencies['SLL'] = array('name'=>'Sierra Leone Leone','symbol'=>'','entity'=>''); 
	$currencies['SOD'] = array('name'=>'Somali Shilling','symbol'=>'','entity'=>''); 
	$currencies['SRG'] = array('name'=>'Surinam Guilder','symbol'=>'','entity'=>''); 
	$currencies['STD'] = array('name'=>'Dobra','symbol'=>'','entity'=>''); 
	$currencies['SVC'] = array('name'=>'El Salvador Colon','symbol'=>'','entity'=>''); 
	$currencies['SYP'] = array('name'=>'Syrian Pound','symbol'=>'','entity'=>''); 
	$currencies['SZL'] = array('name'=>'Swaziland Lilangeni','symbol'=>'','entity'=>''); 
	$currencies['THB'] = array('name'=>'Thai Baht','symbol'=>'','entity'=>''); 
	$currencies['TJR'] = array('name'=>'Tajik Ruble','symbol'=>'','entity'=>''); 
	$currencies['TMM'] = array('name'=>'Manat','symbol'=>'','entity'=>''); 
	$currencies['TND'] = array('name'=>'Tunisian Dollar','symbol'=>'$','entity'=>'&#036;'); 
	$currencies['TOP'] = array('name'=>'Tongan Pa\'anga','symbol'=>'','entity'=>''); 
	$currencies['TPE'] = array('name'=>'Timor Escudo','symbol'=>'','entity'=>''); 
	$currencies['TRL'] = array('name'=>'Turkish Lira','symbol'=>'','entity'=>''); 
	$currencies['TTD'] = array('name'=>'Trinidad and Tobago Dollar','symbol'=>'$','entity'=>'&#036;'); 
	$currencies['TWD'] = array('name'=>'Taiwan Dollar','symbol'=>'$','entity'=>'&#036;'); 
	$currencies['TZS'] = array('name'=>'Tanzanian Shilling','symbol'=>'','entity'=>''); 
	$currencies['UAG'] = array('name'=>'Ukraine Hryvnia','symbol'=>'','entity'=>''); 
	$currencies['UGS'] = array('name'=>'Uganda Shilling','symbol'=>'','entity'=>''); 
	$currencies['USD'] = array('name'=>'US Dollar','symbol'=>'$','entity'=>'&#036;'); 
	$currencies['UYP'] = array('name'=>'Uruguayan Peso','symbol'=>'','entity'=>''); 
	$currencies['UZS'] = array('name'=>'Uzbekistan Sum','symbol'=>'','entity'=>''); 
	$currencies['VND'] = array('name'=>'Vietnamese Dong','symbol'=>'','entity'=>''); 
	$currencies['VUB'] = array('name'=>'Venezuelan Bolivar','symbol'=>'','entity'=>''); 
	$currencies['VUV'] = array('name'=>'Vanuatu Vatu','symbol'=>'','entity'=>''); 
	$currencies['WST'] = array('name'=>'Samoan Tala','symbol'=>'','entity'=>''); 
	$currencies['XAF'] = array('name'=>'CFA Franc BEAC','symbol'=>'','entity'=>''); 
	$currencies['XCD'] = array('name'=>'East Carribean Dollar','symbol'=>'$','entity'=>'&#036;'); 
	$currencies['XOF'] = array('name'=>'CFA Franc BCEAO','symbol'=>'','entity'=>''); 
	$currencies['XPF'] = array('name'=>'CFP Franc','symbol'=>'','entity'=>''); 
	$currencies['YER'] = array('name'=>'Yemeni Rial','symbol'=>'','entity'=>''); 
	$currencies['YUN'] = array('name'=>'Yugoslav New Dinar','symbol'=>'','entity'=>''); 
	$currencies['ZAR'] = array('name'=>'South African Rand','symbol'=>'','entity'=>''); 
	$currencies['ZMK'] = array('name'=>'Zambian Kwacha','symbol'=>'','entity'=>''); 
	$currencies['ZWD'] = array('name'=>'Zimbabwe Dollar','symbol'=>'$','entity'=>'&#036;');
	return $currencies;
}

?>